batch_size: 64
random_state: 42
num_workers: 0
max_epochs: 20
precision: 16
device: mps
num_classes: 10
accumulate_grad_batches: 5


defaults:
  - _self_
  - model: default
  - datamodule: default
  - optim: adamw
  - criterion: cross_entropy
  - lr_scheduler: plateau
  - callbacks: default
  - metrics: default
  - paths: default
  - logger: tensorboard
  - augmentations: default
  - trainer: default